#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=./env/resolve_config.sh
source "${ROOT_DIR}/.flow/scripts/env/resolve_config.sh"

project=""
source_profile=""
output_path="${ROOT_DIR}/migration_kit.tgz"
force="0"

usage() {
  cat <<'EOF'
Usage: .flow/scripts/create_migration_kit.sh --project <name> [options]

Options:
  --project <name>         Целевое имя profile для migration kit (обязательно).
  --source-profile <name>  Profile-источник для безопасных defaults без secrets.
  --output <path>          Путь итогового архива (по умолчанию ./migration_kit.tgz).
  --force                  Перезаписать существующий архив.
  -h, --help               Показать справку.

Examples:
  .flow/scripts/create_migration_kit.sh --project acme
  .flow/scripts/create_migration_kit.sh --project acme --source-profile planka --output /tmp/acme_kit.tgz
EOF
}

slugify() {
  local value="$1"
  value="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
  value="$(printf '%s' "$value" | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g')"
  [[ -n "$value" ]] || value="profile"
  printf '%s' "$value"
}

resolve_source_env_file() {
  local target_profile="$1"
  local candidate=""
  local first_env=""
  local count="0"

  if [[ -n "$source_profile" ]]; then
    candidate="$(codex_resolve_profile_env_file "$(slugify "$source_profile")")"
    [[ -f "$candidate" ]] || {
      echo "Source profile env not found: ${candidate}" >&2
      return 1
    }
    printf '%s' "$candidate"
    return 0
  fi

  if [[ -n "${DAEMON_GH_ENV_FILE:-}" && -f "${DAEMON_GH_ENV_FILE}" ]]; then
    printf '%s' "${DAEMON_GH_ENV_FILE}"
    return 0
  fi

  candidate="$(codex_resolve_profile_env_file "${target_profile}")"
  if [[ -f "$candidate" ]]; then
    printf '%s' "$candidate"
    return 0
  fi

  if [[ -d "$(codex_resolve_flow_profile_config_dir)" ]]; then
    while IFS= read -r env_path; do
      [[ -z "$env_path" ]] && continue
      count=$((count + 1))
      if [[ "$count" == "1" ]]; then
        first_env="$env_path"
      fi
    done <<EOF
$(find "$(codex_resolve_flow_profile_config_dir)" -maxdepth 1 -type f -name '*.env' | sort)
EOF
  fi

  if [[ "$count" == "1" && -n "$first_env" ]]; then
    printf '%s' "$first_env"
    return 0
  fi

  return 1
}

resolve_value() {
  local key="$1"
  local default_value="${2:-}"
  codex_resolve_config_value "$key" "$default_value"
}

write_repo_actions_manifest() {
  local files_destination="$1"
  local secrets_destination="$2"
  local workflows_dir="${ROOT_DIR}/.github/workflows"
  local pr_template="${ROOT_DIR}/.github/pull_request_template.md"
  local workflow_rel=""
  local secret_names=""

  : > "$files_destination"
  : > "$secrets_destination"

  if [[ -d "$workflows_dir" ]]; then
    while IFS= read -r workflow_rel; do
      [[ -n "$workflow_rel" ]] || continue
      printf '%s\n' "$workflow_rel" >> "$files_destination"
    done <<EOF
$(cd "$ROOT_DIR" && find .github/workflows -maxdepth 1 -type f -name '*.yml' | sort)
EOF
  fi

  if [[ -f "$pr_template" ]]; then
    printf '%s\n' ".github/pull_request_template.md" >> "$files_destination"
  fi

  if [[ -d "$workflows_dir" ]]; then
    secret_names="$(
      cd "$ROOT_DIR" &&
      rg -o '[A-Z][A-Z0-9_]+ is required' .github/workflows --no-filename 2>/dev/null \
        | sed 's/ is required$//' \
        | sort -u
    )"
    if [[ -n "$secret_names" ]]; then
      printf '%s\n' "$secret_names" > "$secrets_destination"
    fi
  fi
}

write_profile_sample_env() {
  local destination="$1"
  local target_profile="$2"
  local base_branch="$3"
  local head_branch="$4"
  local auth_bind="$5"
  local auth_port="$6"
  local fallback_enabled="$7"
  local watchdog_interval="$8"
  local launchd_namespace="$9"

  cat > "$destination" <<EOF
# Generated by .flow/scripts/create_migration_kit.sh for profile ${target_profile}
# This file intentionally contains no live secrets from the source project.
# After unpacking in a new repo, run:
#   .flow/scripts/run.sh apply_migration_kit --project ${target_profile}

PROJECT_PROFILE=${target_profile}
GITHUB_REPO=
FLOW_BASE_BRANCH=${base_branch}
FLOW_HEAD_BRANCH=${head_branch}

# PROJECT_NUMBER и PROJECT_OWNER возьми из URL Project v2 в GitHub UI:
#   https://github.com/users/<owner>/projects/<number>
#   https://github.com/orgs/<owner>/projects/<number>
# Либо выведи все проекты owner с title/number/id:
#   gh project list --owner <PROJECT_OWNER> --format json --jq '.projects[] | [.owner.login, .title, (.number|tostring), .id] | @tsv'
# PROJECT_ID (node id, вида PVT_...) GitHub UI не показывает.
# Получить его можно так:
#   gh project view <PROJECT_NUMBER> --owner <PROJECT_OWNER> --format json --jq '.id'
PROJECT_ID=
PROJECT_NUMBER=
PROJECT_OWNER=

# Required for Project v2 operations in the current hybrid flow.
# GitHub UI:
#   Avatar -> Settings -> Developer settings -> Personal access tokens -> Tokens (classic) -> Generate new token
# Required scopes:
#   repo, read:project, project
# Recommended extra scopes for compatibility:
#   read:org, read:discussions
DAEMON_GH_PROJECT_TOKEN=

# Required for daemon/watchdog -> auth-service token exchange.
# Alternative: set DAEMON_GH_TOKEN_FALLBACK_ENABLED=1 and DAEMON_GH_TOKEN.
GH_APP_INTERNAL_SECRET=

# Optional auth endpoint overrides.
GH_APP_BIND=${auth_bind}
GH_APP_PORT=${auth_port}

# Optional emergency fallback token.
DAEMON_GH_TOKEN_FALLBACK_ENABLED=${fallback_enabled}
DAEMON_GH_TOKEN=

# Relative paths are rewritten to absolute in the working .env by apply_migration_kit.
CODEX_STATE_DIR=.flow/state/codex/${target_profile}
FLOW_STATE_DIR=.flow/state/codex/${target_profile}

# Needed so watchdog can restart the correct daemon profile.
WATCHDOG_DAEMON_LABEL=${launchd_namespace}.codex-daemon.${target_profile}
WATCHDOG_DAEMON_INTERVAL_SEC=${watchdog_interval}
EOF
}

write_root_codex_env() {
  local destination="$1"
  local project_slug="$2"
  local auth_bind="$3"
  local auth_port="$4"
  local auth_timeout="$5"
  local auth_token_url="$6"
  local launchd_namespace="$7"

  cat > "$destination" <<EOF
# Generated by .flow/scripts/create_migration_kit.sh
# Copy required values into .env or .env.deploy of the new consumer-project.
# This file lives under .flow/config/root/.env.codex so it does not collide with a product-specific .env.example.

# GitHub App auth-service
FLOW_LAUNCHD_NAMESPACE=${launchd_namespace}
GH_APP_ID=
GH_APP_INSTALLATION_ID=
# Recommended neutral path outside repo:
# GH_APP_PRIVATE_KEY_PATH=<HOME>/.secrets/gh-apps/codex-flow.private-key.pem
GH_APP_PRIVATE_KEY_PATH=
GH_APP_OWNER=
GH_APP_REPO=
GH_APP_INTERNAL_SECRET=
GH_APP_BIND=${auth_bind}
GH_APP_PORT=${auth_port}
GH_APP_TOKEN_SKEW_SEC=300
GH_APP_PM2_APP_NAME=${project_slug}-gh-app-auth
DAEMON_GH_AUTH_TIMEOUT_SEC=${auth_timeout}
DAEMON_GH_AUTH_TOKEN_URL=${auth_token_url}

# Local daemon/watchdog Telegram alerts
DAEMON_TG_BOT_TOKEN=
DAEMON_TG_CHAT_ID=
DAEMON_TG_REMINDER_SEC=1800
DAEMON_TG_GH_DNS_REMINDER_SEC=300
DAEMON_TG_DIRTY_REMINDER_SEC=600

# Ops bot + status dashboard
# If several consumer-projects run on one host, keep OPS_BOT_PORT and OPS_BOT_PM2_APP_NAME unique per project.
OPS_BOT_BIND=127.0.0.1
OPS_BOT_PORT=8790
OPS_BOT_WEBHOOK_PATH=/telegram/webhook
OPS_BOT_WEBHOOK_SECRET=
OPS_BOT_TG_SECRET_TOKEN=
OPS_BOT_ALLOWED_CHAT_IDS=
OPS_BOT_PUBLIC_BASE_URL=
OPS_BOT_REFRESH_SEC=5
OPS_BOT_CMD_TIMEOUT_MS=10000
OPS_BOT_PM2_APP_NAME=${project_slug}-ops-bot
OPS_BOT_TG_BOT_TOKEN=

# Optional split-runtime mode: remote ops bot accepts snapshot/log-summary from local daemon runtime
# OPS_BOT_INGEST_ENABLED=1
# OPS_BOT_INGEST_PATH=/ops/ingest/status
# OPS_BOT_INGEST_SECRET=
# OPS_BOT_SUMMARY_INGEST_PATH=/ops/ingest/log-summary
# OPS_BOT_SUMMARY_INGEST_SECRET=
# OPS_BOT_REMOTE_SNAPSHOT_TTL_SEC=600
# OPS_BOT_REMOTE_SUMMARY_TTL_SEC=1200
# OPS_REMOTE_STATUS_PUSH_ENABLED=1
# OPS_REMOTE_STATUS_PUSH_URL=
# OPS_REMOTE_STATUS_PUSH_SECRET=
# OPS_REMOTE_STATUS_PUSH_TIMEOUT_SEC=6
# OPS_REMOTE_STATUS_PUSH_SOURCE=${project_slug}
# OPS_REMOTE_SUMMARY_PUSH_ENABLED=1
# OPS_REMOTE_SUMMARY_PUSH_URL=
# OPS_REMOTE_SUMMARY_PUSH_SECRET=
# OPS_REMOTE_SUMMARY_PUSH_TIMEOUT_SEC=8
# OPS_REMOTE_SUMMARY_PUSH_SOURCE=${project_slug}
# OPS_REMOTE_SUMMARY_PUSH_HOURS=6
# OPS_REMOTE_SUMMARY_PUSH_MIN_INTERVAL_SEC=300
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)
      [[ $# -ge 2 ]] || { echo "Missing value for --project" >&2; exit 1; }
      project="$2"
      shift 2
      ;;
    --source-profile)
      [[ $# -ge 2 ]] || { echo "Missing value for --source-profile" >&2; exit 1; }
      source_profile="$2"
      shift 2
      ;;
    --output)
      [[ $# -ge 2 ]] || { echo "Missing value for --output" >&2; exit 1; }
      output_path="$2"
      shift 2
      ;;
    --force)
      force="1"
      shift
      ;;
    -h|--help|help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$project" ]]; then
  echo "Option --project is required" >&2
  usage
  exit 1
fi

project_slug="$(slugify "$project")"

if [[ -e "$output_path" && "$force" != "1" ]]; then
  echo "Output archive already exists: ${output_path}" >&2
  echo "Use --force to overwrite it." >&2
  exit 1
fi

source_env_file="$(resolve_source_env_file "$project_slug" || true)"
if [[ -n "$source_env_file" ]]; then
  export DAEMON_GH_ENV_FILE="$source_env_file"
fi

flow_base_branch="$(resolve_value "FLOW_BASE_BRANCH" "main")"
flow_head_branch="$(resolve_value "FLOW_HEAD_BRANCH" "development")"
auth_bind="$(resolve_value "GH_APP_BIND" "127.0.0.1")"
auth_port="$(resolve_value "GH_APP_PORT" "8787")"
fallback_enabled="$(resolve_value "DAEMON_GH_TOKEN_FALLBACK_ENABLED" "")"
if [[ -z "$fallback_enabled" ]]; then
  fallback_enabled="$(resolve_value "CODEX_GH_TOKEN_FALLBACK_ENABLED" "0")"
fi
auth_timeout="$(resolve_value "DAEMON_GH_AUTH_TIMEOUT_SEC" "8")"
auth_token_url="$(resolve_value "DAEMON_GH_AUTH_TOKEN_URL" "")"
launchd_namespace="$(resolve_value "FLOW_LAUNCHD_NAMESPACE" "com.flow")"

watchdog_interval="45"
if [[ -n "$source_env_file" && -f "$source_env_file" ]]; then
  watchdog_interval="$(codex_read_key_from_env_file "$source_env_file" "WATCHDOG_DAEMON_INTERVAL_SEC" || true)"
fi
[[ -n "$watchdog_interval" ]] || watchdog_interval="45"

build_dir="$(mktemp -d "${TMPDIR:-/tmp}/codex_migration_kit.XXXXXX")"
cleanup() {
  rm -rf "$build_dir"
}
trap cleanup EXIT

mkdir -p \
  "${build_dir}/.flow/config/profiles" \
  "${build_dir}/.flow/config/root" \
  "${build_dir}/.flow/launchd" \
  "${build_dir}/.flow/state/codex/${project_slug}" \
  "${build_dir}/.flow/tmp" \
  "${build_dir}/.flow/templates/github"

cp -R "${ROOT_DIR}/.flow/scripts" "${build_dir}/.flow/"
cp -R "${ROOT_DIR}/.flow/docs" "${build_dir}/.flow/"
if [[ -f "${ROOT_DIR}/COMMAND_TEMPLATES.md" ]]; then
  cp "${ROOT_DIR}/COMMAND_TEMPLATES.md" "${build_dir}/COMMAND_TEMPLATES.md"
fi
if [[ -d "${ROOT_DIR}/.github/workflows" ]]; then
  mkdir -p "${build_dir}/.flow/templates/github/workflows"
  cp -R "${ROOT_DIR}/.github/workflows/." "${build_dir}/.flow/templates/github/workflows/"
fi
if [[ -f "${ROOT_DIR}/.github/pull_request_template.md" ]]; then
  cp "${ROOT_DIR}/.github/pull_request_template.md" "${build_dir}/.flow/templates/github/pull_request_template.md"
fi

touch "${build_dir}/.flow/state/codex/${project_slug}/.keep"
touch "${build_dir}/.flow/launchd/.keep"
write_profile_sample_env \
  "${build_dir}/.flow/config/profiles/${project_slug}.sample.env" \
  "$project_slug" \
  "$flow_base_branch" \
  "$flow_head_branch" \
  "$auth_bind" \
  "$auth_port" \
  "$fallback_enabled" \
  "$watchdog_interval" \
  "$launchd_namespace"
write_root_codex_env "${build_dir}/.flow/config/root/.env.codex" "$project_slug" "$auth_bind" "$auth_port" "$auth_timeout" "$auth_token_url" "$launchd_namespace"
write_repo_actions_manifest \
  "${build_dir}/.flow/config/root/github-actions.required-files.txt" \
  "${build_dir}/.flow/config/root/github-actions.required-secrets.txt"

cat > "${build_dir}/.flow/tmp/migration_kit_manifest.env" <<EOF
MIGRATION_KIT_PROJECT=${project_slug}
MIGRATION_KIT_CREATED_AT_UTC=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
MIGRATION_KIT_SOURCE_ENV_FILE=$(basename "${source_env_file:-}")
MIGRATION_KIT_PROFILE_SAMPLE_ENV=.flow/config/profiles/${project_slug}.sample.env
MIGRATION_KIT_PROFILE_ENV_TARGET=.flow/config/profiles/${project_slug}.env
MIGRATION_KIT_CODEX_ENV=.flow/config/root/.env.codex
MIGRATION_KIT_STATE_DIR=.flow/state/codex/${project_slug}
MIGRATION_KIT_DOC_DIR=.flow/docs
MIGRATION_KIT_COMMAND_TEMPLATES=COMMAND_TEMPLATES.md
MIGRATION_KIT_REPO_ACTIONS_TEMPLATE=.flow/templates/github
MIGRATION_KIT_REPO_ACTIONS_FILES=.flow/config/root/github-actions.required-files.txt
MIGRATION_KIT_REPO_ACTIONS_SECRETS=.flow/config/root/github-actions.required-secrets.txt
EOF

mkdir -p "$(dirname "$output_path")"
rm -f "$output_path"
tar -czf "$output_path" -C "$build_dir" .

echo "MIGRATION_KIT_CREATED=${output_path}"
echo "MIGRATION_KIT_PROJECT=${project_slug}"
if [[ -n "$source_env_file" ]]; then
  echo "MIGRATION_KIT_SOURCE_ENV=${source_env_file}"
fi
echo "MIGRATION_KIT_PROFILE_SAMPLE=.flow/config/profiles/${project_slug}.sample.env"
echo "MIGRATION_KIT_CODEX_ENV=.flow/config/root/.env.codex"
echo "MIGRATION_KIT_REPO_ACTIONS=.flow/templates/github"
echo "MIGRATION_KIT_REPO_ACTIONS_SECRETS=.flow/config/root/github-actions.required-secrets.txt"
