#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./env/bootstrap.sh
source "${SCRIPT_DIR}/env/bootstrap.sh"

project=""
source_profile=""
defaults_from="current"
target_repo=""
output_path=""
include_secrets="0"
force="0"

usage() {
  cat <<'EOF'
Usage: .flow/shared/scripts/create_migration_kit.sh --project <name> [options]

Options:
  --project <name>         Целевое имя profile для migration kit (обязательно).
  --defaults-from <mode>   Откуда брать defaults для нового flow.sample.env:
                           current (из текущего flow.env) или sample (из flow.sample.env).
  --source-profile <name>  Legacy profile-источник для defaults-from=current.
  --target-repo <path>     Путь к новому repo (обязательно): в
                           <target-repo>/.flow/migration/ будут записаны
                           do_migration.sh, flow.conf и README.md.
  --output <path>          Явный путь итогового архива. По умолчанию:
                           ./.flow/migration/<project>-migration-kit.tgz
  --include-secrets        Для prefilled flow.env переносить секреты из current source env.
  --force                  Перезаписать существующий архив.
  -h, --help               Показать справку.

Examples:
  .flow/shared/scripts/create_migration_kit.sh --project acme --target-repo <HOME>/sites/acme-app
  .flow/shared/scripts/create_migration_kit.sh --project acme --defaults-from sample --target-repo <HOME>/sites/acme-app
  .flow/shared/scripts/create_migration_kit.sh --project acme --defaults-from current --include-secrets --target-repo <HOME>/sites/acme-app
  .flow/shared/scripts/create_migration_kit.sh --project acme --defaults-from current --source-profile planka --target-repo <HOME>/sites/acme-app --output /tmp/acme_kit.tgz
EOF
}

write_apply_launcher() {
  local destination="$1"
  cat > "$destination" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLKIT_RUNNER="${SCRIPT_DIR}/.flow/shared/scripts/run.sh"

if [[ ! -x "$TOOLKIT_RUNNER" ]]; then
  echo "Toolkit runner not found: ${TOOLKIT_RUNNER}" >&2
  echo "Unpack migration kit in repo root first." >&2
  exit 1
fi

exec "$TOOLKIT_RUNNER" apply_migration_kit "$@"
EOF
  chmod +x "$destination"
}

write_target_migration_config() {
  local destination="$1"
  local project_slug="$2"
  local source_archive_path="$3"
  local source_repo_path="$4"
  local defaults_mode="$5"
  local include_secrets_mode="$6"

  cat > "$destination" <<EOF
# Generated by .flow/shared/scripts/create_migration_kit.sh
MIGRATION_KIT_PROJECT=${project_slug}
MIGRATION_KIT_SOURCE_ARCHIVE=${source_archive_path}
MIGRATION_KIT_SOURCE_REPO=${source_repo_path}
MIGRATION_KIT_BOOTSTRAP_APPLY_REL=apply_migration_kit.sh
MIGRATION_KIT_DEFAULTS_SOURCE=${defaults_mode}
MIGRATION_KIT_INCLUDE_SECRETS=${include_secrets_mode}
EOF
}

write_target_migration_readme() {
  local destination="$1"
  local project_slug="$2"
  local source_archive_path="$3"

  cat > "$destination" <<EOF
# Migration Kit

Для проекта \`${project_slug}\` уже подготовлен migration kit.

Что лежит рядом:
- \`do_migration.sh\` — основной launcher миграции
- \`flow.conf\` — локальная конфигурация миграции

Что делать в новом проекте:
1. Перейти в \`.flow/migration/\`
2. Запустить:
   \`./do_migration.sh\`

Что сделает launcher:
1. Скопирует kit из source repo: \`${source_archive_path}\`
2. Временно положит его в \`.flow/tmp/migration/\`
3. Распакует kit в корень repo
4. Вызовет встроенный \`apply_migration_kit\`
5. Попробует materialize-ить \`/.flow/shared\` как submodule
6. Сохранит локальный migration config в \`.flow/config/flow.conf\`

После завершения:
1. При необходимости пройти wizard:
   \`.flow/shared/scripts/run.sh flow_configurator questionnaire --profile ${project_slug}\`
2. Запустить orchestration:
   \`.flow/shared/scripts/run.sh profile_init orchestrate --profile ${project_slug}\`
EOF
}

write_target_migration_launcher() {
  local destination="$1"
  cat > "$destination" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CONFIG_PATH="${SCRIPT_DIR}/flow.conf"

if [[ ! -f "$CONFIG_PATH" ]]; then
  echo "[migration] flow.conf not found: ${CONFIG_PATH}" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$CONFIG_PATH"
set +a

SOURCE_ARCHIVE_PATH="${MIGRATION_KIT_SOURCE_ARCHIVE:-}"
APPLY_REL="${MIGRATION_KIT_BOOTSTRAP_APPLY_REL:-apply_migration_kit.sh}"
APPLY_PATH="${REPO_ROOT}/${APPLY_REL#./}"
TMP_ARCHIVE_PATH="$(mktemp "${TMPDIR:-/tmp}/codex_migration_kit.XXXXXX")"

cleanup() {
  rm -f "$TMP_ARCHIVE_PATH"
}
trap cleanup EXIT

if [[ -z "$SOURCE_ARCHIVE_PATH" || ! -f "$SOURCE_ARCHIVE_PATH" ]]; then
  echo "[migration] source archive not found: ${SOURCE_ARCHIVE_PATH}" >&2
  exit 1
fi

echo "[migration] step 1/3 downloading kit from ${SOURCE_ARCHIVE_PATH}"
cp "$SOURCE_ARCHIVE_PATH" "$TMP_ARCHIVE_PATH"

echo "[migration] step 2/3 unpacking kit into repo root"
tar -xzf "$TMP_ARCHIVE_PATH" -C "$REPO_ROOT"

if [[ ! -x "$APPLY_PATH" ]]; then
  echo "[migration] apply launcher not found after unpack: ${APPLY_PATH}" >&2
  exit 1
fi

echo "[migration] step 3/3 applying migration config via ${APPLY_REL}"
echo "[migration] apply script will also try to materialize .flow/shared as submodule"
exec "$APPLY_PATH" --project "${MIGRATION_KIT_PROJECT:-}" --migration-config "$CONFIG_PATH" "$@"
EOF
  chmod +x "$destination"
}

slugify() {
  local value="$1"
  value="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
  value="$(printf '%s' "$value" | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g')"
  [[ -n "$value" ]] || value="profile"
  printf '%s' "$value"
}

resolve_source_env_file() {
  local target_profile="$1"
  local candidate=""
  local first_env=""
  local count="0"

  if [[ "$defaults_from" == "sample" ]]; then
    candidate="$(codex_resolve_flow_sample_env_file)"
    [[ -f "$candidate" ]] || {
      echo "Source sample env not found: ${candidate}" >&2
      return 1
    }
    printf '%s' "$candidate"
    return 0
  fi

  if [[ -n "$source_profile" ]]; then
    candidate="$(codex_resolve_profile_env_file "$(slugify "$source_profile")")"
    [[ -f "$candidate" ]] || {
      echo "Source profile env not found: ${candidate}" >&2
      return 1
    }
    printf '%s' "$candidate"
    return 0
  fi

  if [[ -n "${DAEMON_GH_ENV_FILE:-}" && -f "${DAEMON_GH_ENV_FILE}" ]]; then
    printf '%s' "${DAEMON_GH_ENV_FILE}"
    return 0
  fi

  candidate="$(codex_resolve_flow_env_file)"
  if [[ -f "$candidate" ]]; then
    printf '%s' "$candidate"
    return 0
  fi

  candidate="$(codex_resolve_profile_env_file "${target_profile}")"
  if [[ -f "$candidate" ]]; then
    printf '%s' "$candidate"
    return 0
  fi

  if [[ -d "$(codex_resolve_flow_profile_config_dir)" ]]; then
    while IFS= read -r env_path; do
      [[ -z "$env_path" ]] && continue
      count=$((count + 1))
      if [[ "$count" == "1" ]]; then
        first_env="$env_path"
      fi
    done <<EOF
$(find "$(codex_resolve_flow_profile_config_dir)" -maxdepth 1 -type f -name '*.env' | sort)
EOF
  fi

  if [[ "$count" == "1" && -n "$first_env" ]]; then
    printf '%s' "$first_env"
    return 0
  fi

  candidate="$(codex_resolve_flow_sample_env_file)"
  if [[ -f "$candidate" ]]; then
    printf '%s' "$candidate"
    return 0
  fi

  return 1
}

rewrite_env_key() {
  local file_path="$1"
  local key="$2"
  local value="$3"
  local temp_file

  temp_file="$(mktemp "${TMPDIR:-/tmp}/codex_env_rewrite.XXXXXX")"
  awk -v target_key="$key" -v target_value="$value" '
    BEGIN { replaced = 0 }
    $0 ~ ("^" target_key "=") {
      print target_key "=" target_value
      replaced = 1
      next
    }
    { print }
    END {
      if (replaced == 0) {
        print target_key "=" target_value
      }
    }
  ' "$file_path" > "$temp_file"
  mv "$temp_file" "$file_path"
}

clear_env_key() {
  local file_path="$1"
  local key="$2"
  rewrite_env_key "$file_path" "$key" ""
}

resolve_value() {
  local key="$1"
  local default_value="${2:-}"
  codex_resolve_config_value "$key" "$default_value"
}

write_repo_actions_manifest() {
  local files_destination="$1"
  local secrets_destination="$2"
  local workflows_dir="${ROOT_DIR}/.github/workflows"
  local pr_template="${ROOT_DIR}/.github/pull_request_template.md"
  local workflow_rel=""
  local secret_names=""

  : > "$files_destination"
  : > "$secrets_destination"

  if [[ -d "$workflows_dir" ]]; then
    while IFS= read -r workflow_rel; do
      [[ -n "$workflow_rel" ]] || continue
      printf '%s\n' "$workflow_rel" >> "$files_destination"
    done <<EOF
$(cd "$ROOT_DIR" && find .github/workflows -maxdepth 1 -type f -name '*.yml' | sort)
EOF
  fi

  if [[ -f "$pr_template" ]]; then
    printf '%s\n' ".github/pull_request_template.md" >> "$files_destination"
  fi

  if [[ -d "$workflows_dir" ]]; then
    secret_names="$(
      cd "$ROOT_DIR" &&
      rg -o '[A-Z][A-Z0-9_]+ is required' .github/workflows --no-filename 2>/dev/null \
        | sed 's/ is required$//' \
        | sort -u
    )"
    if [[ -n "$secret_names" ]]; then
      printf '%s\n' "$secret_names" > "$secrets_destination"
    fi
  fi
}

write_profile_env_from_source() {
  local destination="$1"
  local source_env_path="$2"
  local defaults_mode="$3"
  local target_profile="$4"
  local watchdog_interval="$5"
  local launchd_namespace="$6"
  local preserve_secrets="$7"
  local comment_mode="$8"
  local line=""
  local key=""
  local value=""
  local source_label=""
  local -a sensitive_keys=(
    DAEMON_GH_PROJECT_TOKEN
    CODEX_GH_PROJECT_TOKEN
    GH_APP_INTERNAL_SECRET
    DAEMON_GH_TOKEN
    CODEX_GH_TOKEN
    DAEMON_TG_BOT_TOKEN
    OPS_BOT_TG_BOT_TOKEN
    OPS_BOT_WEBHOOK_SECRET
    OPS_BOT_TG_SECRET_TOKEN
    OPS_REMOTE_STATUS_PUSH_SECRET
    OPS_REMOTE_SUMMARY_PUSH_SECRET
  )

  if [[ "$defaults_mode" == "sample" ]]; then
    source_label="flow.sample.env"
  else
    source_label="flow.env"
  fi

  {
    cat <<EOF
# Generated by .flow/shared/scripts/create_migration_kit.sh for profile ${target_profile}
# Defaults source: ${source_label}
# Mode: ${comment_mode}
# This file intentionally contains no live secrets from the source project.
# After unpacking in a new repo, run:
#   .flow/shared/scripts/run.sh apply_migration_kit --project ${target_profile}

EOF

    while IFS= read -r line || [[ -n "$line" ]]; do
      if [[ "$line" =~ ^[A-Z][A-Z0-9_]*= ]]; then
        key="${line%%=*}"
        value="${line#*=}"
        case "$key" in
          PROJECT_PROFILE)
            value="${target_profile}"
            ;;
          CODEX_STATE_DIR|FLOW_STATE_DIR)
            value=".flow/state"
            ;;
          WATCHDOG_DAEMON_LABEL)
            value="${launchd_namespace}.codex-daemon.${target_profile}"
            ;;
          WATCHDOG_DAEMON_INTERVAL_SEC)
            value="${watchdog_interval}"
            ;;
          GH_APP_PM2_APP_NAME)
            value="${target_profile}-gh-app-auth"
            ;;
          OPS_BOT_PM2_APP_NAME)
            value="${target_profile}-ops-bot"
            ;;
          OPS_REMOTE_STATUS_PUSH_SOURCE|OPS_REMOTE_SUMMARY_PUSH_SOURCE)
            value="${target_profile}"
            ;;
        esac

        if [[ "$preserve_secrets" != "1" ]]; then
          for sensitive_key in "${sensitive_keys[@]}"; do
            if [[ "$key" == "$sensitive_key" ]]; then
              value=""
              break
            fi
          done
        fi

        printf '%s=%s\n' "$key" "$value"
        continue
      fi
      printf '%s\n' "$line"
    done < "$source_env_path"
  } > "$destination"

  rewrite_env_key "$destination" "PROJECT_PROFILE" "$target_profile"
  rewrite_env_key "$destination" "CODEX_STATE_DIR" ".flow/state"
  rewrite_env_key "$destination" "FLOW_STATE_DIR" ".flow/state"
  rewrite_env_key "$destination" "WATCHDOG_DAEMON_LABEL" "${launchd_namespace}.codex-daemon.${target_profile}"
  rewrite_env_key "$destination" "WATCHDOG_DAEMON_INTERVAL_SEC" "${watchdog_interval}"
  rewrite_env_key "$destination" "GH_APP_PM2_APP_NAME" "${target_profile}-gh-app-auth"
  rewrite_env_key "$destination" "OPS_BOT_PM2_APP_NAME" "${target_profile}-ops-bot"
  rewrite_env_key "$destination" "OPS_REMOTE_STATUS_PUSH_SOURCE" "${target_profile}"
  rewrite_env_key "$destination" "OPS_REMOTE_SUMMARY_PUSH_SOURCE" "${target_profile}"
  if [[ "$preserve_secrets" != "1" ]]; then
    clear_env_key "$destination" "DAEMON_GH_PROJECT_TOKEN"
    clear_env_key "$destination" "CODEX_GH_PROJECT_TOKEN"
    clear_env_key "$destination" "GH_APP_INTERNAL_SECRET"
    clear_env_key "$destination" "DAEMON_GH_TOKEN"
    clear_env_key "$destination" "CODEX_GH_TOKEN"
    clear_env_key "$destination" "DAEMON_TG_BOT_TOKEN"
    clear_env_key "$destination" "OPS_BOT_TG_BOT_TOKEN"
    clear_env_key "$destination" "OPS_BOT_WEBHOOK_SECRET"
    clear_env_key "$destination" "OPS_BOT_TG_SECRET_TOKEN"
    clear_env_key "$destination" "OPS_REMOTE_STATUS_PUSH_SECRET"
    clear_env_key "$destination" "OPS_REMOTE_SUMMARY_PUSH_SECRET"
  fi

  if ! rg -q '^# Prefer interactive wizard for first setup or safe rerun:' "$destination"; then
    cat >> "$destination" <<EOF

# Prefer interactive wizard for first setup or safe rerun:
#   .flow/shared/scripts/run.sh flow_configurator questionnaire --profile ${target_profile}
EOF
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project)
      [[ $# -ge 2 ]] || { echo "Missing value for --project" >&2; exit 1; }
      project="$2"
      shift 2
      ;;
    --source-profile)
      [[ $# -ge 2 ]] || { echo "Missing value for --source-profile" >&2; exit 1; }
      source_profile="$2"
      shift 2
      ;;
    --defaults-from)
      [[ $# -ge 2 ]] || { echo "Missing value for --defaults-from" >&2; exit 1; }
      defaults_from="$2"
      shift 2
      ;;
    --target-repo)
      [[ $# -ge 2 ]] || { echo "Missing value for --target-repo" >&2; exit 1; }
      target_repo="$2"
      shift 2
      ;;
    --include-secrets)
      include_secrets="1"
      shift
      ;;
    --output)
      [[ $# -ge 2 ]] || { echo "Missing value for --output" >&2; exit 1; }
      output_path="$2"
      shift 2
      ;;
    --force)
      force="1"
      shift
      ;;
    -h|--help|help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$project" ]]; then
  echo "Option --project is required" >&2
  usage
  exit 1
fi

if [[ -z "$target_repo" ]]; then
  echo "Option --target-repo is required" >&2
  usage
  exit 1
fi

project_slug="$(slugify "$project")"
if [[ -z "$output_path" ]]; then
  output_path="${ROOT_DIR}/.flow/migration/${project_slug}-migration-kit.tgz"
fi

case "$defaults_from" in
  current|sample)
    ;;
  *)
    echo "Unknown value for --defaults-from: ${defaults_from}" >&2
    echo "Expected one of: current, sample" >&2
    exit 1
    ;;
esac

if [[ -e "$output_path" && "$force" != "1" ]]; then
  echo "Output archive already exists: ${output_path}" >&2
  echo "Use --force to overwrite it." >&2
  exit 1
fi

source_defaults_file="$(resolve_source_env_file "$project_slug" || true)"
if [[ "$defaults_from" == "current" && -n "$source_defaults_file" ]]; then
  export DAEMON_GH_ENV_FILE="$source_defaults_file"
fi

launchd_namespace="$(resolve_value "FLOW_LAUNCHD_NAMESPACE" "com.flow")"

watchdog_interval="45"
if [[ -n "$source_defaults_file" && -f "$source_defaults_file" ]]; then
  watchdog_interval="$(codex_read_key_from_env_file "$source_defaults_file" "WATCHDOG_DAEMON_INTERVAL_SEC" || true)"
fi
[[ -n "$watchdog_interval" ]] || watchdog_interval="45"
if [[ -z "$source_defaults_file" || ! -f "$source_defaults_file" ]]; then
  echo "Could not resolve source env for defaults-from=${defaults_from}." >&2
  exit 1
fi

toolkit_remote_url="$(git -C "${ROOT_DIR}/.flow/shared" remote get-url origin 2>/dev/null || true)"
toolkit_revision="$(git -C "${ROOT_DIR}/.flow/shared" rev-parse HEAD 2>/dev/null || true)"

build_dir="$(mktemp -d "${TMPDIR:-/tmp}/codex_migration_kit.XXXXXX")"
cleanup() {
  rm -rf "$build_dir"
}
trap cleanup EXIT

mkdir -p \
  "${build_dir}/.flow/config" \
  "${build_dir}/.flow/state" \
  "${build_dir}/.flow/tmp" \
  "${build_dir}/.flow/templates/github"

cp -R "${ROOT_DIR}/.flow/shared" "${build_dir}/.flow/"
rm -rf "${build_dir}/.flow/shared/.git"
if [[ -f "${ROOT_DIR}/COMMAND_TEMPLATES.md" ]]; then
  cp "${ROOT_DIR}/COMMAND_TEMPLATES.md" "${build_dir}/COMMAND_TEMPLATES.md"
fi
if [[ -d "${ROOT_DIR}/.github/workflows" ]]; then
  mkdir -p "${build_dir}/.flow/templates/github/workflows"
  cp -R "${ROOT_DIR}/.github/workflows/." "${build_dir}/.flow/templates/github/workflows/"
fi
if [[ -f "${ROOT_DIR}/.github/pull_request_template.md" ]]; then
  cp "${ROOT_DIR}/.github/pull_request_template.md" "${build_dir}/.flow/templates/github/pull_request_template.md"
fi
write_apply_launcher "${build_dir}/apply_migration_kit.sh"

touch "${build_dir}/.flow/state/.keep"
write_profile_env_from_source \
  "${build_dir}/.flow/config/flow.sample.env" \
  "${source_defaults_file}" \
  "${defaults_from}" \
  "$project_slug" \
  "$watchdog_interval" \
  "$launchd_namespace" \
  "0" \
  "safe-sample"
write_profile_env_from_source \
  "${build_dir}/.flow/config/flow.env" \
  "${source_defaults_file}" \
  "${defaults_from}" \
  "$project_slug" \
  "$watchdog_interval" \
  "$launchd_namespace" \
  "$include_secrets" \
  "prefilled-flow-env"
write_repo_actions_manifest \
  "${build_dir}/.flow/templates/github/required-files.txt" \
  "${build_dir}/.flow/templates/github/required-secrets.txt"

cat > "${build_dir}/.flow/tmp/migration_kit_manifest.env" <<EOF
MIGRATION_KIT_PROJECT=${project_slug}
MIGRATION_KIT_CREATED_AT_UTC=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
MIGRATION_KIT_DEFAULTS_SOURCE=${defaults_from}
MIGRATION_KIT_INCLUDE_SECRETS=${include_secrets}
MIGRATION_KIT_SOURCE_ENV_FILE=$(basename "${source_defaults_file:-}")
MIGRATION_KIT_PROFILE_SAMPLE_ENV=.flow/config/flow.sample.env
MIGRATION_KIT_PROFILE_ENV_TARGET=.flow/config/flow.env
MIGRATION_KIT_STATE_DIR=.flow/state
MIGRATION_KIT_TOOLKIT_DIR=.flow/shared
MIGRATION_KIT_DOC_DIR=.flow/shared/docs
MIGRATION_KIT_COMMAND_TEMPLATES=COMMAND_TEMPLATES.md
MIGRATION_KIT_BOOTSTRAP_APPLY=apply_migration_kit.sh
MIGRATION_KIT_TOOLKIT_MODE=submodule_snapshot
MIGRATION_KIT_TOOLKIT_SUBMODULE_URL=${toolkit_remote_url}
MIGRATION_KIT_TOOLKIT_SUBMODULE_REVISION=${toolkit_revision}
MIGRATION_KIT_REPO_ACTIONS_TEMPLATE=.flow/templates/github
MIGRATION_KIT_REPO_ACTIONS_FILES=.flow/templates/github/required-files.txt
MIGRATION_KIT_REPO_ACTIONS_SECRETS=.flow/templates/github/required-secrets.txt
EOF

mkdir -p "$(dirname "$output_path")"
rm -f "$output_path"
tar -czf "$output_path" -C "$build_dir" .

target_migration_dir="${target_repo}/.flow/migration"
target_flow_conf_path="${target_migration_dir}/flow.conf"
target_readme_path="${target_migration_dir}/README.md"
target_launcher_path="${target_migration_dir}/do_migration.sh"

for target_path in "$target_flow_conf_path" "$target_readme_path" "$target_launcher_path"; do
  if [[ -e "$target_path" && "$force" != "1" ]]; then
    echo "Target migration artifact already exists: ${target_path}" >&2
    echo "Use --force to overwrite it." >&2
    exit 1
  fi
done

mkdir -p "$target_migration_dir"
write_target_migration_config \
  "$target_flow_conf_path" \
  "$project_slug" \
  "$output_path" \
  "$ROOT_DIR" \
  "$defaults_from" \
  "$include_secrets"
write_target_migration_readme \
  "$target_readme_path" \
  "$project_slug" \
  "$output_path"
write_target_migration_launcher "$target_launcher_path"

echo "MIGRATION_KIT_TARGET_REPO=${target_repo}"
echo "MIGRATION_KIT_TARGET_FLOW_CONF=${target_flow_conf_path}"
echo "MIGRATION_KIT_TARGET_README=${target_readme_path}"
echo "MIGRATION_KIT_TARGET_LAUNCHER=${target_launcher_path}"
echo "NEXT_STEP=cd ${target_migration_dir} && ./do_migration.sh"

echo "MIGRATION_KIT_CREATED=${output_path}"
echo "MIGRATION_KIT_PROJECT=${project_slug}"
echo "MIGRATION_KIT_DEFAULTS_SOURCE=${defaults_from}"
echo "MIGRATION_KIT_INCLUDE_SECRETS=${include_secrets}"
if [[ -n "$source_defaults_file" ]]; then
  echo "MIGRATION_KIT_SOURCE_ENV=${source_defaults_file}"
fi
echo "MIGRATION_KIT_PROFILE_SAMPLE=.flow/config/flow.sample.env"
echo "MIGRATION_KIT_FLOW_ENV=.flow/config/flow.env"
echo "MIGRATION_KIT_REPO_ACTIONS=.flow/templates/github"
echo "MIGRATION_KIT_REPO_ACTIONS_SECRETS=.flow/templates/github/required-secrets.txt"
